<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BSA-Laptop" failures="1" tests="3" name="com.associateArchitect.Web.testcases.delete_w3schoolprofile" time="79.380" errors="0" timestamp="2023-07-06T10:57:32 IST" skipped="2">
  <testcase classname="com.associateArchitect.Web.testcases.delete_w3schoolprofile" name="deleteprofile" time="41.146">
    <failure message="Delete Profile Testcase is Failed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Delete Profile Testcase is Failed
at org.testng.Assert.fail(Assert.java:87)
at com.associateArchitect.Web.testcases.delete_w3schoolprofile.deleteprofile(delete_w3schoolprofile.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: User Logged in Failed. expected [My learning | W3Schools] but found [W3Schools Online Web Tutorials]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.associateArchitect.Web.testcases.delete_w3schoolprofile.deleteprofile(delete_w3schoolprofile.java:20)
... 28 more
]]>
    </failure>
  </testcase> <!-- deleteprofile -->
  <system-out/>
  <testcase classname="com.associateArchitect.Web.testcases.delete_w3schoolprofile" name="deleteprofile" time="18.813">
    <skipped/>
  </testcase> <!-- deleteprofile -->
  <system-out/>
  <testcase classname="com.associateArchitect.Web.testcases.delete_w3schoolprofile" name="deleteprofile" time="19.421">
    <skipped/>
  </testcase> <!-- deleteprofile -->
  <system-out/>
</testsuite> <!-- com.associateArchitect.Web.testcases.delete_w3schoolprofile -->
